# Dockerfile.dev

# Use Node.js base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Expose port 3010
EXPOSE 3010

# Start the app
CMD ["npm", "start"]
