# docker-compose.yml

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - '3010:3010'
    volumes:
      - ./client:/app
    environment:
      - CHOKIDAR_USEPOLLING=true  # For file change detection on some systems
      - NODE_ENV=development
      - PORT=3010
      - REACT_APP_API_URL=http://localhost:5010
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - '5010:5010'
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase
      - JWT_SECRET=giUQrrraiYeIUhVpage0kWjK7PoW/KROGY6oM+jJ5FU=
    depends_on:
      - db
    command: ["npm", "run", "dev"]

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydatabase
    ports:
      - '5432:5432'  # Optional, for direct access from host
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

