# Dockerfile.dev

# Use Node.js base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Install build dependencies
RUN apk add --no-cache python3 make g++

# Install nodemon globally
RUN npm install -g nodemon

# Install dependencies
COPY package*.json ./

# Install dependencies including dev dependencies
RUN npm install 

# Copy source code
COPY . .

# Expose port 5010
EXPOSE 5010

# Start the app with nodemon for live reloading
CMD ["npm", "run", "dev"]
