# Dockerfile.dev

# Use Node.js base image
FROM node:14-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port 5010
EXPOSE 5010

# Start the app with nodemon for live reloading
CMD ["npm", "run", "dev"]
